"""The email-search agent: tools, the multi-turn rollout loop, and the correctness judge.

The core loop (`run_agent`) is model-agnostic — it talks to any OpenAI-compatible
`AsyncOpenAI` client. That lets the *same* agent run against a closed model for the
baseline (`scripts/baseline.py`) and against the trainable W&B Serverless model during
RL (`rollout`, used by `scripts/train.py`). Faithful to the ART·E example.
"""

from __future__ import annotations

import json
import os
from dataclasses import asdict
from textwrap import dedent

import art
import weave
from langchain_core.utils.function_calling import convert_to_openai_tool
from litellm import acompletion
from openai import AsyncOpenAI
from pydantic import BaseModel, Field
from tenacity import retry, stop_after_attempt

from email_agent.data import FinalAnswer, Scenario, read_email, search_emails

# Turns per episode. Notebook lowers this from 10 to 6 to speed up training.
MAX_TURNS = int(os.environ.get("MAX_TURNS", "6"))
# Judge used for per-answer correctness (0/1 metric). Configurable; OpenAI-compatible.
JUDGE_MODEL = os.environ.get("JUDGE_MODEL", "openai/gpt-4o-mini")


class ProjectTrajectory(art.Trajectory):
    final_answer: FinalAnswer | None = None


class EmailScenario(BaseModel):
    step: int
    scenario: Scenario


class CorrectnessJudgeResponse(BaseModel):
    reasoning: str = Field(description="Explanation of the reasoning process.")
    accept: bool = Field(description="Whether the AI answer should be accepted.")


@retry(stop=stop_after_attempt(3))
async def judge_correctness(scenario: Scenario, answer: str) -> CorrectnessJudgeResponse:
    """LLM judge: does the AI answer contain the reference answer's relevant info?"""
    system_prompt = dedent(
        """
        You are given a question, the reference answer (labelled **Reference answer**), and an answer generated by an AI assistant (labelled **AI answer**).

        Your task is to decide whether the AI answer is correct and should be accepted. You should accept the answer if it contains the relevant information from the reference answer. You should not accept the answer if it is missing information relevant to the question, or if it contradicts the reference answer.
        """
    )
    messages = [
        {"role": "system", "content": system_prompt},
        {
            "role": "user",
            "content": (
                f"Question: {scenario.question}\n"
                f"Reference answer: {scenario.answer}\n"
                f"AI answer: {answer}"
            ),
        },
    ]
    response = await acompletion(
        model=JUDGE_MODEL, messages=messages, response_format=CorrectnessJudgeResponse
    )
    raw_content = response.choices[0].message.content or "{}"
    try:
        return CorrectnessJudgeResponse.model_validate_json(raw_content)
    except Exception as e:  # noqa: BLE001
        return CorrectnessJudgeResponse(reasoning=f"Parse error: {e}\nRaw: {raw_content}", accept=False)


def _build_tools(scenario: Scenario):
    """Bind the search/read/final-answer tools to a scenario's inbox + query date."""

    def search_inbox(keywords: list[str]) -> list[dict]:
        """Search the inbox for emails matching the given keywords."""
        results = search_emails(
            inbox=scenario.inbox_address, keywords=keywords, sent_before=scenario.query_date
        )
        return [asdict(result) for result in results]

    def return_final_answer(answer: str, reference_message_ids: list[str]) -> FinalAnswer:
        """Return the final answer and the message IDs of the emails used to generate it."""
        return FinalAnswer(answer=answer, source_ids=reference_message_ids)

    tools = [search_inbox, read_email, return_final_answer]
    tools_by_name = {t.__name__: t for t in tools}
    openai_tools = [convert_to_openai_tool(t) for t in tools]
    return tools_by_name, openai_tools


async def run_agent(
    scenario: Scenario,
    *,
    client: AsyncOpenAI,
    model_name: str,
    step: int = 0,
    judge: bool = True,
    temperature: float = 1.0,
) -> ProjectTrajectory:
    """Run the email agent for one scenario against any OpenAI-compatible endpoint."""
    traj = ProjectTrajectory(
        reward=0.0,
        messages_and_choices=[],
        metadata={"scenario_id": scenario.id, "step": step},
    )
    system_prompt = dedent(
        f"""
        You are an email search agent. You are given a user query and a list of tools you can use to search the user's email. Use the tools to search the user's emails and find the answer to the user's query. You may take up to {MAX_TURNS} turns to find the answer, so if your first search doesn't find the answer, you can try with different keywords.

        User's email address is {scenario.inbox_address}
        Today's date is {scenario.query_date}
        """
    )
    traj.messages_and_choices = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": scenario.question},
    ]

    tools_by_name, openai_tools = _build_tools(scenario)
    traj.tools = openai_tools

    for _ in range(MAX_TURNS):
        response = await client.chat.completions.create(
            model=model_name,
            temperature=temperature,
            messages=traj.messages(),
            tools=traj.tools,
        )
        response_message = response.choices[0].message
        traj.messages_and_choices.append(response.choices[0])

        if not response_message.tool_calls:
            return traj

        try:
            for tool_call in response_message.tool_calls:
                tool_name = tool_call.function.name
                if tool_name not in tools_by_name:
                    continue
                tool_args = json.loads(tool_call.function.arguments)
                result = tools_by_name[tool_name](**tool_args)
                traj.messages_and_choices.append(
                    {
                        "role": "tool",
                        "tool_call_id": tool_call.id,
                        "name": tool_name,
                        "content": str(result),
                    }
                )
                if tool_name == "return_final_answer":
                    traj.final_answer = result
                    if judge and traj.final_answer:
                        judged = await judge_correctness(scenario, traj.final_answer.answer)
                        traj.metrics["correct"] = float(judged.accept)
                    return traj
        except Exception as e:  # noqa: BLE001
            print(f"Error executing tool call: {e}")
            return traj

    return traj


@weave.op
async def rollout(model: art.Model, email_scenario: EmailScenario) -> ProjectTrajectory:
    """ART rollout: run the agent against the trainable model's inference endpoint."""
    client = AsyncOpenAI(
        base_url=model.inference_base_url,
        api_key=model.inference_api_key,
    )
    return await run_agent(
        email_scenario.scenario,
        client=client,
        model_name=model.get_inference_name(),
        step=email_scenario.step,
    )
